name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: yarn run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Set up authentication for GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          
      - name: Install dependencies
        run: yarn install

      - name: Deploy to GitHub Pages using gh-pages
        run: |
          yarn add gh-pages
          yarn run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure the GitHub token is stored as a secret
