name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm  # This will cache the yarn dependencies too.

      - name: Install dependencies
        run: yarn install  # Using yarn instead of pnpm

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: yarn run build  # Running the build with yarn

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'  # Ensure 'build/' is correct. Change if necessary.

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install  # Install dependencies again for deployment

      - name: Deploy to GitHub Pages using gh-pages
        run: |
          yarn add gh-pages  # Install gh-pages package
          yarn run deploy   # Run the deploy script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for deployment

    # Ensure `GH_TOKEN` is added to your GitHub secrets if it doesn't exist already.
